### ISSUE TITLE
Controller select function return ObjectLiteral

### ISSUE THREAD

**Issue by GyuBa** [Koreatech-Mongle/chameleon-platform#11]

**Comment by GyuBa** [comment]
All the find of Controller give string type argument to `source.getRepository`

It causes problem, So controller `source.getRepository('User')` change to  `source.getRepository(User)`

## Example
https://github.com/Koreatech-Mongle/chameleon-platform/blob/feature/upload-image/src/controller/ImageController.ts#L28
### Before
``` typescript
const imageRepository = source.getRepository('Image');
```
### After
``` typescript
const imageRepository = source.getRepository(Image);
```

**Comment by refracta** [comment]
PR 처리됨 해결되었으면 닫을 것

**Comment by GyuBa** [comment]
이거 왜 자동으로 안 닫힘
